### ISSUE TITLE
Problem running the bot on ScienceBirds

### ISSUE THREAD

**Issue by lucasvictorsp** [dwolter/BamBirds#1]
Hello,

I'm trying to do some tests with Angry Birds' bots.

I downloaded the project and I tried to run with the instructions given (README.md), but got the error (java.io.FileNotFoundException: Prolog \ planner \ ShotCandidatePlanner.pl (The system cannot find the path specified))

I found "Prolog/planner/ShotCandidatePlanner.pl" in "planner/src/main/Prolog/...", so I copied and pasted it into the root folder.

The error is gone, and the client connects to the server, but the bot doesn't start the game. Can you tell me why this is happening?

**Comment by dwolter** [comment]
Hi,
in case you are running Windows: apparently symlinks don't work when cloning the agent, so just create the link manually or copy the file. Our agent cannot start the game, it is up to the server to do so: just click the start button.

**Comment by lucasvictorsp** [comment]
Thanks for your help.

When I start the server doesn't open any pop-Up windows, and the server is waiting for new connections.

How could I start the server for client begin to play?

Thank you again.


![BamBirds](https://user-images.githubusercontent.com/14021651/81713401-32dd2300-944c-11ea-8cac-90d1dc324154.png)

**Comment by sargreal** [comment]
From what it looks like, the prolog is not starting. You have the default swipl location for Linux selected, but on windows you would need 
```properties
# If swipl is in $PATH
PATH_TO_SWIPL=swipl
# otherwise path without spaces, for example
PATH_TO_SWIPL=C:\\swipl\\bin\\swipl
```
Why it does not show errors I have no clue

**Comment by lucasvictorsp** [comment]
I got it.

I replaced the configuration file and it worked.

Thanks for your help.
